apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: lvms-operator-metrics-cert
  labels:
    app.kubernetes.io/name: lvms-operator
    app.kubernetes.io/compose: metrics
  name: lvms-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: lvms-operator
