apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: vg-manager-metrics-cert
  labels:
    app.kubernetes.io/name: vg-manager
    app.kubernetes.io/compose: metrics
  name: vg-manager-metrics-service
  namespace: system
spec:
  ports:
    - name: vg-manager-https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: vg-manager
