apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lvms-operator
    app.kubernetes.io/compose: metrics
  name: lvms-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: lvms-operator
