apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: topolvm-metrics-cert
  labels:
    app.kubernetes.io/compose: metrics
    app.kubernetes.io/part-of: lvms-provisioner
  name: topolvm-node-metrics
  namespace: system
spec:
  ports:
    - name: topolvm-metrics
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: topolvm-node
