apiVersion: v1
kind: Template
metadata:
  name: lvms-operator-build
  annotations:
    description: "Template for building the lvms operator."
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: lvms-operator
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: lvms-operator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: lvms-operator:latest
    source:
      git:
        uri: ${GIT_URL}
        ref: ${GIT_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
parameters:
- description: 'URL for the LVMS Operator git repository'
  name: GIT_URL
  value: https://github.com/openshift/lvm-operator
- description: 'Git branch'
  name: GIT_BRANCH
  value: main
